site_name: 'godon'
site_description: 'Project around Paralellized Metaheuristics driven Infrastructure Optimization'
site_author: 'Matthias Tafelmeier'
repo_url: https://github.com/godon-dev/godon
repo_name: GitHub
copyright: "Copyright &copy; 2019 - Today; Matthias Tafelmeier"
theme:
  name: "material"
  features:
    - navigation.footer
  palette:
    # Dark mode palette
    - scheme: slate
      primary: teal
      accent: cyan
  favicon: assets/icon.png
  logo: assets/logo_small.png
nav:
    - '': index.md
    - Documentation:
        - Introduction: introduction.md
        - Architecture: architecture.md
        - Usage: usage.md
